export const GET_COMPANY_SETTINGS_REQUESTED ='GET_COMPANY_SETTINGS_REQUESTED'
export const GET_COMPANY_SETTINGS_SUCCESS ='GET_COMPANY_SETTINGS_SUCCESS'
export const GET_COMPANY_SETTINGS_FAILED ='GET_COMPANY_SETTINGS_FAILED'

export const GET_CONTACTCOMPANY_SETTINGS_REQUESTED ='GET_CONTACTCOMPANY_SETTINGS_REQUESTED'
export const GET_CONTACTCOMPANY_SETTINGS_SUCCESS ='GET_CONTACTCOMPANY_SETTINGS_SUCCESS'
export const GET_CONTACTCOMPANY_SETTINGS_FAILED ='GET_CONTACTCOMPANY_SETTINGS_FAILED'

export const ADD_COMPANY_SETTINGS_REQUESTED ='ADD_COMPANY_SETTINGS_REQUESTED'
export const ADD_COMPANY_SETTINGS_SUCCESS ='ADD_COMPANY_SETTINGS_SUCCESS'
export const ADD_COMPANY_SETTINGS_FAILED ='ADD_COMPANY_SETTINGS_FAILED'


export const GET_COMPANY_SETTINGS_BY_KEY_REQUESTED ='GET_COMPANY_SETTINGS_BY_KEY_REQUESTED'
export const GET_COMPANY_SETTINGS_BY_KEY_SUCCESS ='GET_COMPANY_SETTINGS_BY_KEY_SUCCESS'
export const GET_COMPANY_SETTINGS_BY_KEY_FAILED ='GET_COMPANY_SETTINGS_BY_KEY_FAILED'


export const GET_LOGO_REQUESTED ='GET_LOGO_REQUESTED'
export const GET_LOGO_SUCCESS ='GET_LOGO_SUCCESS'
export const GET_LOGO_FAILED ='GET_COMPANY_SETTINGS_BY_KEY_FAILED'



export const SET_COMPANY_SETTINGS_SUCCESS_ALERT = "SET_COMPANY_SETTINGS_SUCCESS_ALERT"
export const SET_COMPANY_SETTINGS_ERROR_ALERT = "SET_COMPANY_SETTINGS_ERROR_ALERT"


export const SET_LOGO = "SET_LOGO"