export const GET_KAM_REQUESTED ='GET_KAM_REQUESTED'
export const GET_KAM_SUCCESS ='GET_KAM_SUCCESS'
export const GET_KAM_FAILED ='GET_KAM_FAILED'

export const SET_KAM_SUCCESS_ALERT = "SET_KAM_SUCCESS_ALERT"
export const SET_KAM_ERROR_ALERT = "SET_KAM_ERROR_ALERT"





