export const GET_KAM_REQUESTED = 'GET_KAM_REQUESTED'
export const GET_KAM_SUCCESS = 'GET_KAM_SUCCESS'
export const GET_KAM_FAILED = 'GET_KAM_FAILED'

export const GET_KAM_DETAILS_REQUESTED ='GET_KAM_DETAILS_REQUESTED'
export const GET_KAM_DETAILS_SUCCESS ='GET_KAM_DETAILS_SUCCESS'
export const GET_KAM_DETAILS_FAILED ='GET_KAM_DETAILS_FAILED'

export const GET_ALLKAM_REQUESTED ='GET_ALLKAM_REQUESTED'
export const GET_ALLKAM_SUCCESS ='GET_ALLKAM_SUCCESS'
export const GET_ALLKAM_FAILED ='GET_ALLKAM_FAILED'

export const ADD_KAM_REQUESTED ='ADD_KAM_REQUESTED'
export const ADD_KAM_SUCCESS ='ADD_KAM_SUCCESS'
export const ADD_KAM_FAILED ='ADD_KAM_FAILED'

export const DELETE_KAM_REQUESTED ='DELETE_KAM_REQUESTED'
export const DELETE_KAM_SUCCESS ='DELETE_KAM_SUCCESS'
export const DELETE_KAM_FAILED ='DELETE_KAM_FAILED'

export const UPDATE_ERROR_KAM_FAILED ='UPDATE_ERROR_KAM_FAILED'

export const SET_KAM_SUCCESS_ALERT ='SET_KAM_SUCCESS_ALERT'
export const SET_KAM_ERROR_ALERT ='SET_KAM_ERROR_ALERT'
