export const GET_PAYMENT_REQUESTED ='GET_PAYMENT_REQUESTED'
export const GET_PAYMENT_SUCCESS ='GET_PAYMENT_SUCCESS'
export const GET_PAYMENT_FAILED ='GET_PAYMENT_FAILED'

export const GET_PAYMENT_DETAILS_REQUESTED ='GET_PAYMENT_DETAILS_REQUESTED'
export const GET_PAYMENT_DETAILS_SUCCESS ='GET_PAYMENT_DETAILS_SUCCESS'
export const GET_PAYMENT_DETAILS_FAILED ='GET_PAYMENT_DETAILS_FAILED'


export const GET_PAYMENT_TYPES_REQUESTED ='GET_PAYMENT_TYPES_REQUESTED'
export const GET_PAYMENT_TYPES_SUCCESS ='GET_PAYMENT_TYPES_SUCCESS'
export const GET_PAYMENT_TYPES_FAILED ='GET_PAYMENT_TYPES_FAILED'


export const GET_DUE_INVOICES_REQUESTED ='GET_DUE_INVOICES_REQUESTED'
export const GET_DUE_INVOICES_SUCCESS ='GET_DUE_INVOICES_SUCCESS'
export const GET_DUE_INVOICES_FAILED ='GET_DUE_INVOICES_FAILED'


export const GET_CLIENT_BALANCE_REQUESTED ='GET_CLIENT_BALANCE_REQUESTED'
export const GET_CLIENT_BALANCE_SUCCESS ='GET_CLIENT_BALANCE_SUCCESS'
export const GET_CLIENT_BALANCE_FAILED ='GET_CLIENT_BALANCE_FAILED'

