export const GET_PAYMENT_REQUESTED ='GET_PAYMENT_REQUESTED'
export const GET_PAYMENT_SUCCESS ='GET_PAYMENT_SUCCESS'
export const GET_PAYMENT_FAILED ='GET_PAYMENT_FAILED'

export const GET_PAYMENT_DETAILS_REQUESTED ='GET_PAYMENT_DETAILS_REQUESTED'
export const GET_PAYMENT_DETAILS_SUCCESS ='GET_PAYMENT_DETAILS_SUCCESS'
export const GET_PAYMENT_DETAILS_FAILED ='GET_PAYMENT_DETAILS_FAILED'

export const GET_ALLPAYMENT_REQUESTED ='GET_ALLPAYMENT_REQUESTED'
export const GET_ALLPAYMENT_SUCCESS ='GET_ALLPAYMENT_SUCCESS'
export const GET_ALLPAYMENT_FAILED ='GET_ALLPAYMENT_FAILED'

export const GET_PAYMENT_TYPES_REQUESTED ='GET_PAYMENT_TYPES_REQUESTED'
export const GET_PAYMENT_TYPES_SUCCESS ='GET_PAYMENT_TYPES_SUCCESS'
export const GET_PAYMENT_TYPES_FAILED ='GET_PAYMENT_TYPES_FAILED'


export const GET_DUE_INVOICES_REQUESTED ='GET_DUE_INVOICES_REQUESTED'
export const GET_DUE_INVOICES_SUCCESS ='GET_DUE_INVOICES_SUCCESS'
export const GET_DUE_INVOICES_FAILED ='GET_DUE_INVOICES_FAILED'


export const GET_CLIENT_BALANCE_REQUESTED ='GET_CLIENT_BALANCE_REQUESTED'
export const GET_CLIENT_BALANCE_SUCCESS ='GET_CLIENT_BALANCE_SUCCESS'
export const GET_CLIENT_BALANCE_FAILED ='GET_CLIENT_BALANCE_FAILED'


export const GET_PAYMENT_DETAILS_SUCCESS_MSG ='GET_PAYMENT_DETAILS_SUCCESS_MSG'

export const SET_PAYMENT_SUCCESS_ALERT ='SET_PAYMENT_SUCCESS_ALERT'
export const SET_PAYMENT_ERROR_ALERT ='SET_PAYMENT_ERROR_ALERT'

export const ADD_PAYMENT_REQUESTED ='ADD_PAYMENT_REQUESTED'
export const ADD_PAYMENT_SUCCESS ='ADD_PAYMENT_SUCCESS'
export const ADD_PAYMENT_FAILED ='ADD_PAYMENT_FAILED'


export const ADD_INVOICE_PAYMENT_REQUESTED ='ADD_INVOICE_PAYMENT_REQUESTED'
export const ADD_INVOICE_PAYMENT_SUCCESS ='ADD_INVOICE_PAYMENT_SUCCESS'
export const ADD_INVOICE_PAYMENT_FAILED ='ADD_INVOICE_PAYMENT_FAILED'


export const RESET_PAYMENT_REDUCER_STATE='RESET_PAYMENT_REDUCER_STATE'
export const CLEAR_SUBMIT_SUCCESS_MESSAGE ='CLEAR_SUBMIT_SUCCESS_MESSAGE'
export const CLEAR_SUBMIT_ERROR_MESSAGE ='CLEAR_SUBMIT_ERROR_MESSAGE'
export const CLEAR_DUE_INVOICES ='CLEAR_DUE_INVOICES'
