export const GET_CONTACT_REQUESTED ='GET_CONTACT_REQUESTED'
export const GET_CONTACT_SUCCESS ='GET_CONTACT_SUCCESS'
export const GET_CONTACT_FAILED ='GET_CONTACT_FAILED'

export const GET_ALLCONTACT_REQUESTED ='GET_ALLCONTACT_REQUESTED'
export const GET_ALLCONTACT_SUCCESS ='GET_ALLCONTACT_SUCCESS'
export const GET_ALLCONTACT_FAILED ='GET_ALLCONTACT_FAILED'

export const ADD_CONTACT_REQUESTED ='ADD_CONTACT_REQUESTED'
export const ADD_CONTACT_SUCCESS ='ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAILED ='ADD_CONTACT_FAILED'

export const DELETE_CONTACT_REQUESTED ='DELETE_CONTACT_REQUESTED'
export const DELETE_CONTACT_SUCCESS ='DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILED ='DELETE_CONTACT_FAILED'



